######################################################################
# Automatically generated by qmake (3.0) Sun Sep 29 21:40:40 2019
######################################################################

TEMPLATE = app
TARGET = cs331hw01
INCLUDEPATH += .

# Input
SOURCES += main.cpp
